name: madmom
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - opencv
  - portaudio
  - pip
  - pip:
      - -r requirements-dev.txt
      - pyfftw
      - black
      - pre-commit
      - prospector
